// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VelastoProductionSystem.Data;

#nullable disable

namespace VelastoProductionSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260317003243_AddYarnToMasterlistSpsDoubleLayer")]
    partial class AddYarnToMasterlistSpsDoubleLayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VelastoProductionSystem.Models.DimensionReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("InnerDiameter1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InnerDiameter2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InnerDiameter3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InnerDiameter4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InnerDiameter5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InnerDiameterStandard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("InnerThickness1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InnerThickness2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InnerThickness3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InnerThickness4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("InnerThickness5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InnerThicknessStandard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductionReportId")
                        .HasColumnType("int");

                    b.Property<int?>("QtyActPanung")
                        .HasColumnType("int");

                    b.Property<int?>("QtyNGDimensi")
                        .HasColumnType("int");

                    b.Property<int?>("QtyNGVisual")
                        .HasColumnType("int");

                    b.Property<int?>("QtyOK")
                        .HasColumnType("int");

                    b.Property<int?>("QtyStdPanung")
                        .HasColumnType("int");

                    b.Property<int?>("QtyTarget")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SpiralPitchActual")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SpiralPitchStandard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalThickness1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalThickness2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalThickness3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalThickness4")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalThickness5")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TotalThicknessStandard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VisualCheckNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VisualCheckOK")
                        .HasColumnType("bit");

                    b.Property<string>("VisualCheckStandard")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductionReportId");

                    b.ToTable("DimensionReadings");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.LotTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualQty")
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BomText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompoundCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CompoundQty")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DaftarKomponen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastPrintedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LotPackaging")
                        .HasColumnType("int");

                    b.Property<string>("LotTagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MesinCheck")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NGReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoLot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Plant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrintCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PrintedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductionReportId")
                        .HasColumnType("int");

                    b.Property<int?>("QtyNG")
                        .HasColumnType("int");

                    b.Property<int?>("QtyOK")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubconCheck")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TanggalCheck")
                        .HasColumnType("datetime2");

                    b.Property<int>("TargetQty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LotTagNumber")
                        .IsUnique();

                    b.HasIndex("PartNumber");

                    b.HasIndex("ProductionReportId");

                    b.ToTable("LotTags");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.MasterlistSpsDoubleLayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AmMeter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChillerWaterTemp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverDie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuttingSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cylinder1_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cylinder1_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cylinder2_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cylinder2_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcelId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feed1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feed2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formulasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadTemp1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadTemp2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerTube")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Machine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkingColour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkingSort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeshScreen1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeshScreen2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nipple")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdSensor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OuterCover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pressure1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pressure2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevisionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevisionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScrewSpeed1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScrewSpeed2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScrewTemp1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScrewTemp2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelisihTebal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TakeUpConveyorSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TebalInner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TebalOuter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TebalTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextMarkingMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToleranceInner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToleranceOuter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TubeDie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UseLimitsInner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UseLimitsOuter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yarn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MasterlistSpsDoubleLayers");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.NowProducing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CHS2LTargetBenang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHS2LTargetDH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHS2LTargetMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CHS2LTargetWaktu")
                        .HasColumnType("int");

                    b.Property<string>("CHS3LTargetBenang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHS3LTargetDH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHS3LTargetMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CHS3LTargetWaktu")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DandoriEndProdTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DandoriStartProdTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialInner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialInnerLotNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaterialInnerSG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaterialMiddle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialMiddleLotNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaterialMiddleSG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MaterialOuter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialOuterLotNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaterialOuterSG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProductionEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProductionStartTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SPVCheck")
                        .HasColumnType("bit");

                    b.Property<string>("SPVCheckBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SPVCheckTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yarn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NowProducings");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.PackingStandard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualQty")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DH")
                        .HasColumnType("int");

                    b.Property<int>("Dandori")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NACode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StdQty")
                        .HasColumnType("int");

                    b.Property<string>("VinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NACode")
                        .IsUnique();

                    b.ToTable("PackingStandards");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ProductionReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CaterpillarGap")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ChillerWaterTemp")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ControlValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ConveyorRatio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CoolConveyorSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("Cylinder1TempInner")
                        .HasColumnType("int");

                    b.Property<int?>("Cylinder1TempOuter")
                        .HasColumnType("int");

                    b.Property<int?>("Cylinder2TempInner")
                        .HasColumnType("int");

                    b.Property<int?>("Cylinder2TempOuter")
                        .HasColumnType("int");

                    b.Property<int?>("Cylinder3TempInner")
                        .HasColumnType("int");

                    b.Property<int?>("Cylinder3TempOuter")
                        .HasColumnType("int");

                    b.Property<int?>("FeedRollRatioInner")
                        .HasColumnType("int");

                    b.Property<int?>("FeedRollRatioOuter")
                        .HasColumnType("int");

                    b.Property<int?>("HeadTempInner")
                        .HasColumnType("int");

                    b.Property<int?>("HeadTempOuter")
                        .HasColumnType("int");

                    b.Property<decimal?>("HoseSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PresetTemp")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PressureInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PressureOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductionReportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ScrewSpeedInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ScrewSpeedOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ScrewTempInner")
                        .HasColumnType("int");

                    b.Property<int?>("ScrewTempOuter")
                        .HasColumnType("int");

                    b.Property<decimal?>("SpiralPitchDisplay")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SpiralPitchSetting")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SpiralSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TakeupConveyorSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("UnsmoothSurface")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ProductionReportId");

                    b.ToTable("ProductionReadings");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ProductionReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CoverDieOK")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DandoriEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DandoriStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HoseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerMaterialActual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerMaterialLotNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InnerMaterialSG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("MiddleDieOK")
                        .HasColumnType("bit");

                    b.Property<int>("NgDimension")
                        .HasColumnType("int");

                    b.Property<int>("NgVisual")
                        .HasColumnType("int");

                    b.Property<bool>("NippleDieOK")
                        .HasColumnType("bit");

                    b.Property<string>("OuterMaterial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OuterMaterialActual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OuterMaterialLotNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("OuterMaterialSG")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProductionEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProductionStartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("QtyOk")
                        .HasColumnType("int");

                    b.Property<int>("QtyTarget")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SpacerDieOK")
                        .HasColumnType("bit");

                    b.Property<string>("StandardLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StandardParameterSettingId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ToleranceDieOK")
                        .HasColumnType("bit");

                    b.Property<bool>("TubeDieOK")
                        .HasColumnType("bit");

                    b.Property<string>("VinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yarn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YarnActual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber");

                    b.HasIndex("ProductionDate");

                    b.HasIndex("StandardParameterSettingId");

                    b.ToTable("ProductionReports");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.StandardParameterSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AirPressureA")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CaterpillarGap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChillerWaterTemp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControlValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConveyorRatio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoolConveyorSpeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CoverDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cylinder1Temp")
                        .HasColumnType("int");

                    b.Property<int>("Cylinder2Temp")
                        .HasColumnType("int");

                    b.Property<int>("Cylinder3Temp")
                        .HasColumnType("int");

                    b.Property<string>("Diameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FeedRollRatio")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("HeadTemp")
                        .HasColumnType("int");

                    b.Property<string>("HoseSpeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InnerDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("InnerMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LayerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkingMaterialColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MarkingMaterialInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MarkingMaterialOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("MeshScreen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MiddleDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OuterDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("OuterMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PresetTemp")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PresetValve")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Pressure")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("ScrewSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ScrewTemp")
                        .HasColumnType("int");

                    b.Property<decimal>("SpacerDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SpiralPitch")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SpiralPitchDisplay")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SpiralSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SpiralSpeedDisplay")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TakeupConveyorSpeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tol_CoverDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Tol_MiddleDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Tol_OuterDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Tol_SpiralPitch")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Tol_TubeDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ToleranceDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TubeDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnsmoothSurface")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("YarnType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerName");

                    b.HasIndex("DocumentNumber");

                    b.ToTable("StandardParameterSettings");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.DimensionReading", b =>
                {
                    b.HasOne("VelastoProductionSystem.Models.ProductionReport", "ProductionReport")
                        .WithMany()
                        .HasForeignKey("ProductionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionReport");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.LotTag", b =>
                {
                    b.HasOne("VelastoProductionSystem.Models.ProductionReport", "ProductionReport")
                        .WithMany()
                        .HasForeignKey("ProductionReportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProductionReport");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ProductionReading", b =>
                {
                    b.HasOne("VelastoProductionSystem.Models.ProductionReport", "ProductionReport")
                        .WithMany("ProductionReadings")
                        .HasForeignKey("ProductionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionReport");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ProductionReport", b =>
                {
                    b.HasOne("VelastoProductionSystem.Models.StandardParameterSetting", "StandardParameterSetting")
                        .WithMany()
                        .HasForeignKey("StandardParameterSettingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StandardParameterSetting");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ProductionReport", b =>
                {
                    b.Navigation("ProductionReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
