// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VelastoProductionSystem.Data;

#nullable disable

namespace VelastoProductionSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260528015402_ChangeSpsIdToStringInDimensionReport")]
    partial class ChangeSpsIdToStringInDimensionReport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VelastoProductionSystem.Models.DimensionMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DimensionReportId")
                        .HasColumnType("int");

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PointName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("R1")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("R2")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("R3")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("R4")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("R5")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("R6")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("RecordedTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ScaleValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("StandardDimension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeSection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DimensionReportId");

                    b.ToTable("DimensionMeasurements");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.DimensionReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ByPass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimensionDisplay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NgDimension")
                        .HasColumnType("int");

                    b.Property<int>("NgVisual")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("QtyOk")
                        .HasColumnType("int");

                    b.Property<int>("QtyTarget")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Shift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yarn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DimensionReports");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.DimensionSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DimensionReportId")
                        .HasColumnType("int");

                    b.Property<int>("NgDimension")
                        .HasColumnType("int");

                    b.Property<int>("NgVisual")
                        .HasColumnType("int");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtyOk")
                        .HasColumnType("int");

                    b.Property<int>("QtyTarget")
                        .HasColumnType("int");

                    b.Property<string>("StandardLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VinCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DimensionReportId");

                    b.ToTable("DimensionSummaries");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CapacityPerHour")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Line")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("YearMade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.PartMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompoundCombo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompoundInner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompoundMiddle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompoundOuter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CtAwal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CtMinus20")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jumat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kamis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Minggu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NeedKgInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("NeedKgMiddle")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("NeedKgOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PartCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rabu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sabtu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SecPerPcs")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Selasa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PartMasters");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.PlanningMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Compound")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompoundCombo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompoundInner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompoundMiddle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompoundOuter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CtAwal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CtMinus20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateShiftString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Menit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeedKgInner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeedKgMiddle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeedKgOuter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanTargetPcs")
                        .HasColumnType("int");

                    b.Property<string>("WaktuMulai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaktuSelesai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlanningMasters");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ProductionMaterialLot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LayerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LotNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductionReportId")
                        .HasColumnType("int");

                    b.Property<decimal?>("SGValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18, 4)");

                    b.HasKey("Id");

                    b.HasIndex("ProductionReportId");

                    b.ToTable("ProductionMaterialLots");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ProductionReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CaterpillarGap")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ChillerWaterTemp")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ControlValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ConveyorRatio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CoolConveyorSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("Cylinder1TempInner")
                        .HasColumnType("int");

                    b.Property<int?>("Cylinder1TempOuter")
                        .HasColumnType("int");

                    b.Property<int?>("Cylinder2TempInner")
                        .HasColumnType("int");

                    b.Property<int?>("Cylinder2TempOuter")
                        .HasColumnType("int");

                    b.Property<int?>("Cylinder3TempInner")
                        .HasColumnType("int");

                    b.Property<int?>("Cylinder3TempOuter")
                        .HasColumnType("int");

                    b.Property<int?>("FeedRollRatioInner")
                        .HasColumnType("int");

                    b.Property<int?>("FeedRollRatioOuter")
                        .HasColumnType("int");

                    b.Property<int?>("HeadTempInner")
                        .HasColumnType("int");

                    b.Property<int?>("HeadTempOuter")
                        .HasColumnType("int");

                    b.Property<decimal?>("HoseSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InnerDiameter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InnerThicknessX")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InnerThicknessY")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PresetTemp")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PresetValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PressureInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PressureOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductionReportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ScrewSpeedInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ScrewSpeedOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ScrewTempInner")
                        .HasColumnType("int");

                    b.Property<int?>("ScrewTempOuter")
                        .HasColumnType("int");

                    b.Property<decimal?>("SpiralPitch")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SpiralPitchDisplay")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SpiralPitchSetting")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SpiralSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TakeupConveyorSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TotalThicknessX")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TotalThicknessY")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("UnsmoothSurface")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("VisualCheck")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductionReportId");

                    b.ToTable("ProductionReadings");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ProductionReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedBySignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckedBySignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CheckedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CoverDieFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverDieInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CoverDieOK")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAC_Akhir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAC_Awal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAI_Akhir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DAI_Awal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DRAC_Akhir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DRAC_Awal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DRAI_Akhir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DRAI_Awal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DandoriEndEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DandoriEndStartTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DandoriEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DandoriStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dimension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmbossMarkContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmbossMarkDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("InitCaterpillarGap")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitChillerWaterTemp")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitControlValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitConveyorRatio")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitCoolConveyorSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitCylinder1TempInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitCylinder1TempOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitCylinder2TempInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitCylinder2TempOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitCylinder3TempInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitCylinder3TempOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitFeedRollRatioInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitFeedRollRatioOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitHeadTempInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitHeadTempOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitHoseSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitPresetValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitPressureInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitPressureOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitScrewSpeedInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitScrewSpeedOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitScrewTempInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitScrewTempOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitSpiralPitchDisplay")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitSpiralPitchSetting")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitSpiralSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitTakeupConveyorSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitUnsmoothSurface")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("InnerMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerMaterialActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerMaterialLotNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("InnerMaterialSG")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ItemCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MeshInner10Before")
                        .HasColumnType("bit");

                    b.Property<bool>("MeshInner40Before")
                        .HasColumnType("bit");

                    b.Property<string>("MeshInnerCheck")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MeshOuter10Before")
                        .HasColumnType("bit");

                    b.Property<bool>("MeshOuter40Before")
                        .HasColumnType("bit");

                    b.Property<string>("MeshOuterCheck")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleDieFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleDieInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MiddleDieOK")
                        .HasColumnType("bit");

                    b.Property<string>("MiddleMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleMaterialActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleMaterialLotNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MiddleMaterialSG")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("NgDimension")
                        .HasColumnType("int");

                    b.Property<int>("NgVisual")
                        .HasColumnType("int");

                    b.Property<string>("NippleDieFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NippleDieInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NippleDieOK")
                        .HasColumnType("bit");

                    b.Property<string>("OuterMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OuterMaterialActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OuterMaterialLotNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OuterMaterialSG")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProductionEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProductionStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("QcCond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QcRes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QcSurf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtyOk")
                        .HasColumnType("int");

                    b.Property<int>("QtyTarget")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Shift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpacerDieFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpacerDieInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SpacerDieOK")
                        .HasColumnType("bit");

                    b.Property<string>("SpsId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ToleranceDieOK")
                        .HasColumnType("bit");

                    b.Property<string>("ToleranceFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToleranceInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TubeDieFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TubeDieInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TubeDieOK")
                        .HasColumnType("bit");

                    b.Property<string>("VinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WasteCoverAkhir")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("WasteCoverAwal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("WasteInnerAkhir")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("WasteInnerAwal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("WasteWeightAkhir")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("WasteWeightAwal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Yarn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YarnActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YarnLotNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber");

                    b.HasIndex("ProductionDate");

                    b.ToTable("ProductionReports");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.SensorIngestLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("IngestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("MetricValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int?>("ProductionReportId")
                        .HasColumnType("int");

                    b.Property<string>("Quality")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("SensorTimestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Unit")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasFilter("[IdempotencyKey] IS NOT NULL");

                    b.HasIndex("ProductionReportId");

                    b.HasIndex("MachineCode", "SensorTimestamp");

                    b.ToTable("SensorIngestLogs");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ShiftMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ShiftMasters");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.SpsItemList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ItemList")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber");

                    b.ToTable("SpsItemLists");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.SpsNoDoc", b =>
                {
                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ADistance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ADistance_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ADistance_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ADistance_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("AmMeter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AmMeter2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AmMeter2_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("AmMeter2_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("AmMeter2_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("AmMeter3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("AmMeter3_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("AmMeter3_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("AmMeter3_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("AmMeter_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("AmMeter_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("AmMeter_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CaterpillarGap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CaterpillarGap_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CaterpillarGap_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CaterpillarGap_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ChillerWaterTemp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ChillerWaterTemp_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ChillerWaterTemp_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ChillerWaterTemp_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ControlValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ControlValue_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ControlValue_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ControlValue_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ConveyorRatio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ConveyorRatio_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ConveyorRatio_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ConveyorRatio_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CoolConveyorSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoolConveyorSpeed2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CoolConveyorSpeed2_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CoolConveyorSpeed2_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CoolConveyorSpeed2_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CoolConveyorSpeed_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CoolConveyorSpeed_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CoolConveyorSpeed_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CoverDie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CoverDie_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CoverDie_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CoverDie_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CurrentValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuttingSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CuttingSpeed_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CuttingSpeed_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CuttingSpeed_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Cylinder1_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cylinder1_1_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder1_1_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder1_1_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Cylinder1_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cylinder1_2_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder1_2_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder1_2_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Cylinder1_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cylinder1_3_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder1_3_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder1_3_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Cylinder2_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cylinder2_1_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder2_1_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder2_1_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Cylinder2_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cylinder2_2_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder2_2_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder2_2_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Cylinder2_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cylinder2_3_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder2_3_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder2_3_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Cylinder3_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cylinder3_1_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder3_1_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder3_1_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Cylinder3_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cylinder3_2_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder3_2_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder3_2_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Cylinder3_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Cylinder3_3_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder3_3_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Cylinder3_3_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("DancerPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DancerPosition_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("DancerPosition_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("DancerPosition_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Dimensi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feed1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Feed1_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Feed1_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Feed1_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Feed2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Feed2_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Feed2_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Feed2_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Feed3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Feed3_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Feed3_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Feed3_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("FeedRollRatio1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FeedRollRatio1_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("FeedRollRatio1_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("FeedRollRatio1_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("FeedRollRatio2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FeedRollRatio2_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("FeedRollRatio2_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("FeedRollRatio2_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("FeedRollRatio3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("FeedRollRatio3_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("FeedRollRatio3_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("FeedRollRatio3_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Formulasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadTemp1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HeadTemp1_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("HeadTemp1_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("HeadTemp1_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("HeadTemp2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HeadTemp2_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("HeadTemp2_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("HeadTemp2_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("HeadTemp3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HeadTemp3_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("HeadTemp3_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("HeadTemp3_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("HoseSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HoseSpeed_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("HoseSpeed_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("HoseSpeed_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("HoseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerLCL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerMax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerMidLCL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerMidMax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerMidMin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerMidTarget")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerMidTol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerMidUCL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerMin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerTarget")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerTol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerTube")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerUCL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Machine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkingColour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkingSort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeshDim1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MeshDim1_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MeshDim1_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MeshDim1_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("MeshDim2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MeshDim2_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MeshDim2_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MeshDim2_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("MeshDim3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MeshDim3_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MeshDim3_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MeshDim3_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("MeshScreen1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeshScreen2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeshScreen3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleDie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MiddleDie_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MiddleDie_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("MiddleDie_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("MiddleTube")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nipple")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Nipple_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Nipple_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Nipple_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdSensor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OdSensor_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("OdSensor_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("OdSensor_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("OuterCover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PitchYarn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PitchYarn_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PitchYarn_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PitchYarn_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PresetValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PresetValue_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PresetValue_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PresetValue_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Pressure1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Pressure1_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Pressure1_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Pressure1_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Pressure2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Pressure2_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Pressure2_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Pressure2_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Pressure3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Pressure3_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Pressure3_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("Pressure3_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("RevisionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevisionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScrewSpeed1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ScrewSpeed1_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ScrewSpeed1_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ScrewSpeed1_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ScrewSpeed2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ScrewSpeed2_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ScrewSpeed2_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ScrewSpeed2_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ScrewSpeed3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ScrewSpeed3_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ScrewSpeed3_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ScrewSpeed3_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ScrewTemp1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ScrewTemp1_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ScrewTemp1_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ScrewTemp1_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ScrewTemp2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ScrewTemp2_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ScrewTemp2_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ScrewTemp2_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ScrewTemp3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ScrewTemp3_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ScrewTemp3_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ScrewTemp3_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SelisihTebal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SelisihTebal_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SelisihTebal_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SelisihTebal_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SpacerDie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SpacerDie_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SpacerDie_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SpacerDie_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SpiralPitchDisplay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SpiralPitchDisplay_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SpiralPitchDisplay_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SpiralPitchDisplay_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SpiralPitchSetting")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SpiralPitchSetting_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SpiralPitchSetting_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SpiralPitchSetting_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SpiralSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SpiralSpeed_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SpiralSpeed_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SpiralSpeed_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TakeUpConveyorSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TakeUpConveyorSpeed_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TakeUpConveyorSpeed_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TakeUpConveyorSpeed_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TebalInner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TebalInnerMiddle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TebalInnerMiddle_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TebalInnerMiddle_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TebalInnerMiddle_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TebalInner_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TebalInner_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TebalInner_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TebalOuter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TebalOuter_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TebalOuter_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TebalOuter_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TebalTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TebalTotal_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TebalTotal_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TebalTotal_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TensionYarnInner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TensionYarnOuter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextMarkingMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThickLCL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThickMax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThickMin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThickTarget")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThickTol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThickUCL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToleranceInner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ToleranceInner_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ToleranceInner_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ToleranceInner_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ToleranceOuter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ToleranceOuter_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ToleranceOuter_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ToleranceOuter_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ToleranceSpiralPitch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ToleranceSpiralPitch_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ToleranceSpiralPitch_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ToleranceSpiralPitch_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TotalLCL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalMax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalMin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalTarget")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalTol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalUCL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TubeDie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TubeDie_Asli")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TubeDie_Max")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TubeDie_Min")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UnsmoothSurface")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UseLimitsInner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UseLimitsMiddle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UseLimitsOuter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yarn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentNumber");

                    b.ToTable("SpsNoDocs");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.DimensionMeasurement", b =>
                {
                    b.HasOne("VelastoProductionSystem.Models.DimensionReport", "DimensionReport")
                        .WithMany("Measurements")
                        .HasForeignKey("DimensionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DimensionReport");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.DimensionSummary", b =>
                {
                    b.HasOne("VelastoProductionSystem.Models.DimensionReport", "DimensionReport")
                        .WithMany("Summaries")
                        .HasForeignKey("DimensionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DimensionReport");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ProductionMaterialLot", b =>
                {
                    b.HasOne("VelastoProductionSystem.Models.ProductionReport", "ProductionReport")
                        .WithMany("MaterialLots")
                        .HasForeignKey("ProductionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionReport");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ProductionReading", b =>
                {
                    b.HasOne("VelastoProductionSystem.Models.ProductionReport", "ProductionReport")
                        .WithMany("ProductionReadings")
                        .HasForeignKey("ProductionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionReport");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.SensorIngestLog", b =>
                {
                    b.HasOne("VelastoProductionSystem.Models.ProductionReport", "ProductionReport")
                        .WithMany()
                        .HasForeignKey("ProductionReportId");

                    b.Navigation("ProductionReport");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.SpsItemList", b =>
                {
                    b.HasOne("VelastoProductionSystem.Models.SpsNoDoc", "SpsNoDoc")
                        .WithMany("ItemLists")
                        .HasForeignKey("DocumentNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SpsNoDoc");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.DimensionReport", b =>
                {
                    b.Navigation("Measurements");

                    b.Navigation("Summaries");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ProductionReport", b =>
                {
                    b.Navigation("MaterialLots");

                    b.Navigation("ProductionReadings");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.SpsNoDoc", b =>
                {
                    b.Navigation("ItemLists");
                });
#pragma warning restore 612, 618
        }
    }
}
