// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VelastoProductionSystem.Data;

#nullable disable

namespace VelastoProductionSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260401012029_AddMeshParameters2")]
    partial class AddMeshParameters2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VelastoProductionSystem.Models.DailyPlanActivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("ActualEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ActualQty")
                        .HasColumnType("int");

                    b.Property<string>("ActualStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DailyPlanExecutionId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("PartName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("PlanEnd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanQty")
                        .HasColumnType("int");

                    b.Property<string>("PlanStart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DailyPlanExecutionId");

                    b.ToTable("DailyPlanActivities");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.DailyPlanExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FinishMesin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LineStopMinutes")
                        .HasColumnType("int");

                    b.Property<string>("LineStopNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pic1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pic2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartMesin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DailyPlanExecutions");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.DimensionMeasurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DimensionReportId")
                        .HasColumnType("int");

                    b.Property<string>("Frequency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PointName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("R1")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("R2")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("R3")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("R4")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("R5")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("RecordedTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ScaleValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("StandardDimension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimeSection")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DimensionReportId");

                    b.ToTable("DimensionMeasurements");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.DimensionReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ByPass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimensionDisplay")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NgDimension")
                        .HasColumnType("int");

                    b.Property<int>("NgVisual")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductionReportId")
                        .HasColumnType("int");

                    b.Property<int>("QtyOk")
                        .HasColumnType("int");

                    b.Property<int>("QtyTarget")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yarn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DimensionReports");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.LotTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualQty")
                        .HasColumnType("int");

                    b.Property<string>("Barcode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BomText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompoundCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CompoundQty")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DaftarKomponen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastPrintedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("LotPackaging")
                        .HasColumnType("int");

                    b.Property<string>("LotTagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MesinCheck")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NGReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoLot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Plant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrintCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PrintedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductionReportId")
                        .HasColumnType("int");

                    b.Property<int?>("QtyNG")
                        .HasColumnType("int");

                    b.Property<int?>("QtyOK")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubconCheck")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TanggalCheck")
                        .HasColumnType("datetime2");

                    b.Property<int>("TargetQty")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LotTagNumber")
                        .IsUnique();

                    b.HasIndex("PartNumber");

                    b.HasIndex("ProductionReportId");

                    b.ToTable("LotTags");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.Machine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CapacityPerHour")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Line")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextMaintenanceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("YearMade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.MasterlistSpsDoubleLayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AmMeter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChillerWaterTemp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverDie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CuttingSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cylinder1_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cylinder1_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cylinder2_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cylinder2_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dimensi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcelId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feed1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Feed2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Formulasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadTemp1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HeadTemp2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerTube")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Machine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkingColour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkingSort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeshScreen1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeshScreen2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nipple")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdSensor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OuterCover")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pressure1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pressure2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevisionDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RevisionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScrewSpeed1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScrewSpeed2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScrewTemp1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScrewTemp2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SelisihTebal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TakeUpConveyorSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TebalInner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TebalOuter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TebalTotal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextMarkingMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToleranceInner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToleranceOuter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TubeDie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UseLimitsInner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UseLimitsOuter")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MasterlistSpsDoubleLayers");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.NowProducing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CHS2LTargetBenang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHS2LTargetDH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHS2LTargetMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CHS2LTargetWaktu")
                        .HasColumnType("int");

                    b.Property<string>("CHS3LTargetBenang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHS3LTargetDH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CHS3LTargetMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CHS3LTargetWaktu")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DandoriEndProdTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DandoriStartProdTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialInner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialInnerLotNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaterialInnerSG")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("MaterialMiddle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialMiddleLotNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaterialMiddleSG")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("MaterialOuter")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaterialOuterLotNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaterialOuterSG")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProductionEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProductionStartTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("SPVCheck")
                        .HasColumnType("bit");

                    b.Property<string>("SPVCheckBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SPVCheckTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yarn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NowProducings");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.PackingStandard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualQty")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DH")
                        .HasColumnType("int");

                    b.Property<int>("Dandori")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NACode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StdQty")
                        .HasColumnType("int");

                    b.Property<string>("VinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NACode")
                        .IsUnique();

                    b.ToTable("PackingStandards");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.PartMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompoundCombo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompoundInner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompoundOuter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CtAwal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("CtMinus20")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ImportedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jumat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kamis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Minggu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("NeedKgInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("NeedKgOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("PartCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rabu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sabtu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SecPerPcs")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Selasa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senin")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PartMasters");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.PlanningMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Compound")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompoundCombo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompoundInner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompoundOuter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CtAwal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CtMinus20")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateShiftString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Menit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeedKgInner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NeedKgOuter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartName1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PartName2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanTargetPcs")
                        .HasColumnType("int");

                    b.Property<string>("WaktuMulai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WaktuSelesai")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlanningMasters");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ProductionReading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CaterpillarGap")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ChillerWaterTemp")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ControlValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ConveyorRatio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CoolConveyorSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("Cylinder1TempInner")
                        .HasColumnType("int");

                    b.Property<int?>("Cylinder1TempOuter")
                        .HasColumnType("int");

                    b.Property<int?>("Cylinder2TempInner")
                        .HasColumnType("int");

                    b.Property<int?>("Cylinder2TempOuter")
                        .HasColumnType("int");

                    b.Property<int?>("Cylinder3TempInner")
                        .HasColumnType("int");

                    b.Property<int?>("Cylinder3TempOuter")
                        .HasColumnType("int");

                    b.Property<int?>("FeedRollRatioInner")
                        .HasColumnType("int");

                    b.Property<int?>("FeedRollRatioOuter")
                        .HasColumnType("int");

                    b.Property<int?>("HeadTempInner")
                        .HasColumnType("int");

                    b.Property<int?>("HeadTempOuter")
                        .HasColumnType("int");

                    b.Property<decimal?>("HoseSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InnerDiameter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InnerThicknessX")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InnerThicknessY")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PresetTemp")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PresetValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PressureInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("PressureOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductionReportId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReadingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecordedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ScrewSpeedInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ScrewSpeedOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ScrewTempInner")
                        .HasColumnType("int");

                    b.Property<int?>("ScrewTempOuter")
                        .HasColumnType("int");

                    b.Property<decimal?>("SpiralPitch")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SpiralPitchDisplay")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SpiralPitchSetting")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("SpiralSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TakeupConveyorSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TotalThicknessX")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("TotalThicknessY")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("UnsmoothSurface")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("VisualCheck")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductionReportId");

                    b.ToTable("ProductionReadings");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ProductionReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActualLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CheckedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverDieFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverDieInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CoverDieOK")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DandoriEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DandoriStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Dimension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EmbossMarkContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmbossMarkDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("InitCaterpillarGap")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitChillerWaterTemp")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitControlValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitConveyorRatio")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitCoolConveyorSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitCylinder1TempInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitCylinder1TempOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitCylinder2TempInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitCylinder2TempOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitCylinder3TempInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitCylinder3TempOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitFeedRollRatioInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitFeedRollRatioOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitHeadTempInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitHeadTempOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitHoseSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitPresetValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitPressureInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitPressureOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitScrewSpeedInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitScrewSpeedOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitScrewTempInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitScrewTempOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitSpiralPitchDisplay")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitSpiralPitchSetting")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitSpiralSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitTakeupConveyorSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("InitUnsmoothSurface")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("InnerMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerMaterialActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InnerMaterialLotNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("InnerMaterialSG")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<bool>("MeshInner10Before")
                        .HasColumnType("bit");

                    b.Property<bool>("MeshInner40Before")
                        .HasColumnType("bit");

                    b.Property<string>("MeshInnerCheck")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MeshOuter10Before")
                        .HasColumnType("bit");

                    b.Property<bool>("MeshOuter40Before")
                        .HasColumnType("bit");

                    b.Property<string>("MeshOuterCheck")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleDieFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleDieInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("MiddleDieOK")
                        .HasColumnType("bit");

                    b.Property<int>("NgDimension")
                        .HasColumnType("int");

                    b.Property<int>("NgVisual")
                        .HasColumnType("int");

                    b.Property<string>("NippleDieFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NippleDieInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NippleDieOK")
                        .HasColumnType("bit");

                    b.Property<string>("OuterMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OuterMaterialActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OuterMaterialLotNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("OuterMaterialSG")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("ProductionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProductionEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ProductionStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("QcCond")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QcRes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QcSurf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QtyOk")
                        .HasColumnType("int");

                    b.Property<int>("QtyTarget")
                        .HasColumnType("int");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<string>("Shift")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpacerDieFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpacerDieInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SpacerDieOK")
                        .HasColumnType("bit");

                    b.Property<string>("StandardLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StandardParameterSettingId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ToleranceDieOK")
                        .HasColumnType("bit");

                    b.Property<string>("ToleranceFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToleranceInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TubeDieFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TubeDieInitial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TubeDieOK")
                        .HasColumnType("bit");

                    b.Property<string>("VinCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WasteCoverAkhir")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("WasteCoverAwal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("WasteInnerAkhir")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("WasteInnerAwal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("WasteWeightAkhir")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("WasteWeightAwal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Yarn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YarnActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YarnLotNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber");

                    b.HasIndex("ProductionDate");

                    b.HasIndex("StandardParameterSettingId");

                    b.ToTable("ProductionReports");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ShiftMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ShiftMasters");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.StandardParameterSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AirPressureA")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CaterpillarGap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChillerWaterTemp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControlValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConveyorRatio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoolConveyorSpeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CoverDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cylinder1Temp")
                        .HasColumnType("int");

                    b.Property<int>("Cylinder2Temp")
                        .HasColumnType("int");

                    b.Property<int>("Cylinder3Temp")
                        .HasColumnType("int");

                    b.Property<string>("Diameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FeedRollRatio")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("HeadTemp")
                        .HasColumnType("int");

                    b.Property<string>("HoseSpeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoseType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InnerDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("InnerMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ItemList")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LayerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MarkingMaterialColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MarkingMaterialInner")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MarkingMaterialOuter")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("MeshScreen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MiddleDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("OuterDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("OuterMaterial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PresetTemp")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PresetValve")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Pressure")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RevisionNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("ScrewSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ScrewTemp")
                        .HasColumnType("int");

                    b.Property<decimal>("SpacerDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SpiralPitch")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SpiralPitchDisplay")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SpiralSpeed")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("SpiralSpeedDisplay")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("TakeupConveyorSpeed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Tol_CoverDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Tol_MiddleDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Tol_OuterDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Tol_SpiralPitch")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Tol_TubeDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ToleranceDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TubeDie")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UnsmoothSurface")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("YarnType")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerName");

                    b.HasIndex("DocumentNumber");

                    b.ToTable("StandardParameterSettings");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.DailyPlanActivity", b =>
                {
                    b.HasOne("VelastoProductionSystem.Models.DailyPlanExecution", "DailyPlanExecution")
                        .WithMany("Activities")
                        .HasForeignKey("DailyPlanExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DailyPlanExecution");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.DimensionMeasurement", b =>
                {
                    b.HasOne("VelastoProductionSystem.Models.DimensionReport", "DimensionReport")
                        .WithMany("Measurements")
                        .HasForeignKey("DimensionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DimensionReport");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.LotTag", b =>
                {
                    b.HasOne("VelastoProductionSystem.Models.ProductionReport", "ProductionReport")
                        .WithMany()
                        .HasForeignKey("ProductionReportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ProductionReport");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ProductionReading", b =>
                {
                    b.HasOne("VelastoProductionSystem.Models.ProductionReport", "ProductionReport")
                        .WithMany("ProductionReadings")
                        .HasForeignKey("ProductionReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionReport");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ProductionReport", b =>
                {
                    b.HasOne("VelastoProductionSystem.Models.StandardParameterSetting", "StandardParameterSetting")
                        .WithMany()
                        .HasForeignKey("StandardParameterSettingId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("StandardParameterSetting");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.DailyPlanExecution", b =>
                {
                    b.Navigation("Activities");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.DimensionReport", b =>
                {
                    b.Navigation("Measurements");
                });

            modelBuilder.Entity("VelastoProductionSystem.Models.ProductionReport", b =>
                {
                    b.Navigation("ProductionReadings");
                });
#pragma warning restore 612, 618
        }
    }
}
