using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace VelastoProductionSystem.Migrations
{
    /// <inheritdoc />
    public partial class CreateSpsNoDocAndItemList : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "SpsNoDocs",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ExcelId = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    No = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Machine = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DocumentNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RevisionNumber = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Customer = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    RevisionDate = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Formulasi = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HoseType = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Dimensi = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Material = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerTube = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OuterCover = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MiddleTube = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UseLimitsInner = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UseLimitsOuter = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UseLimitsMiddle = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Nipple = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TubeDie = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CoverDie = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MiddleDie = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SpacerDie = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ADistance = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Yarn = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TensionYarnInner = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TensionYarnOuter = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MeshDim1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MeshScreen1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MeshDim2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MeshScreen2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MeshDim3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MeshScreen3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HeadTemp1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HeadTemp2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Cylinder1_1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Cylinder1_2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Cylinder2_1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Cylinder2_2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Cylinder3_1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Cylinder3_2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Cylinder3_3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HeadTemp3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Cylinder1_3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Cylinder2_3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ScrewTemp3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Feed1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Feed2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ScrewTemp1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ScrewTemp2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ScrewSpeed1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ScrewSpeed2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Pressure1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Pressure2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Feed3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ScrewSpeed3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Pressure3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AmMeter = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    OdSensor = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MarkingSort = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TextMarkingMaterial = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MarkingColour = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ChillerWaterTemp = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CuttingSpeed = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TakeUpConveyorSpeed = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ToleranceInner = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ToleranceOuter = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TebalInner = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TebalInnerMiddle = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TebalOuter = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TebalTotal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SelisihTebal = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ToleranceSpiralPitch = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    MachineCode = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PitchYarn = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FeedRollRatio1 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FeedRollRatio2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    FeedRollRatio3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CurrentValue = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AmMeter2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    AmMeter3 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    PresetValue = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ControlValue = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SpiralPitchSetting = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SpiralPitchDisplay = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    SpiralSpeed = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    HoseSpeed = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    UnsmoothSurface = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    DancerPosition = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CaterpillarGap = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CoolConveyorSpeed = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    CoolConveyorSpeed2 = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ConveyorRatio = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerTarget = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerTol = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerLCL = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMin = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerUCL = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMidTarget = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMidTol = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMidLCL = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMidMin = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMidUCL = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    InnerMidMax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ThickTarget = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ThickTol = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ThickLCL = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ThickMin = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ThickUCL = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    ThickMax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TotalTarget = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TotalTol = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TotalLCL = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TotalMin = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TotalUCL = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    TotalMax = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Nipple_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Nipple_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Nipple_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TubeDie_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TubeDie_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TubeDie_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    CoverDie_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    CoverDie_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    CoverDie_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    MiddleDie_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    MiddleDie_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    MiddleDie_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    SpacerDie_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    SpacerDie_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    SpacerDie_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ADistance_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ADistance_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ADistance_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    MeshDim1_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    MeshDim1_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    MeshDim1_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    MeshDim2_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    MeshDim2_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    MeshDim2_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    MeshDim3_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    MeshDim3_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    MeshDim3_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    HeadTemp1_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    HeadTemp1_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    HeadTemp1_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    HeadTemp2_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    HeadTemp2_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    HeadTemp2_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    HeadTemp3_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    HeadTemp3_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    HeadTemp3_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder1_1_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder1_1_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder1_1_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder1_2_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder1_2_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder1_2_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder1_3_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder1_3_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder1_3_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder2_1_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder2_1_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder2_1_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder2_2_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder2_2_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder2_2_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder2_3_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder2_3_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder2_3_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder3_1_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder3_1_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder3_1_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder3_2_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder3_2_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder3_2_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder3_3_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder3_3_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Cylinder3_3_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewTemp1_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewTemp1_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewTemp1_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewTemp2_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewTemp2_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewTemp2_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewTemp3_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewTemp3_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewTemp3_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewSpeed1_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewSpeed1_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewSpeed1_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewSpeed2_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewSpeed2_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewSpeed2_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewSpeed3_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewSpeed3_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ScrewSpeed3_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Pressure1_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Pressure1_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Pressure1_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Pressure2_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Pressure2_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Pressure2_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Pressure3_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Pressure3_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Pressure3_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    HoseSpeed_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    HoseSpeed_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    HoseSpeed_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TakeUpConveyorSpeed_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TakeUpConveyorSpeed_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TakeUpConveyorSpeed_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ChillerWaterTemp_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ChillerWaterTemp_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ChillerWaterTemp_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Feed1_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Feed1_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Feed1_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Feed2_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Feed2_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Feed2_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Feed3_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Feed3_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    Feed3_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    FeedRollRatio1_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    FeedRollRatio1_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    FeedRollRatio1_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    FeedRollRatio2_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    FeedRollRatio2_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    FeedRollRatio2_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    FeedRollRatio3_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    FeedRollRatio3_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    FeedRollRatio3_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    CaterpillarGap_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    CaterpillarGap_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    CaterpillarGap_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    SpiralSpeed_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    SpiralSpeed_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    SpiralSpeed_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TebalInner_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TebalInner_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TebalInner_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TebalOuter_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TebalOuter_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TebalOuter_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TebalTotal_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TebalTotal_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TebalTotal_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TebalInnerMiddle_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TebalInnerMiddle_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    TebalInnerMiddle_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    AmMeter_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    AmMeter_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    AmMeter_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    AmMeter2_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    AmMeter2_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    AmMeter2_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    AmMeter3_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    AmMeter3_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    AmMeter3_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    PresetValue_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    PresetValue_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    PresetValue_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ControlValue_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ControlValue_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ControlValue_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    SpiralPitchSetting_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    SpiralPitchSetting_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    SpiralPitchSetting_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    SpiralPitchDisplay_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    SpiralPitchDisplay_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    SpiralPitchDisplay_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    CoolConveyorSpeed_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    CoolConveyorSpeed_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    CoolConveyorSpeed_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    CoolConveyorSpeed2_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    CoolConveyorSpeed2_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    CoolConveyorSpeed2_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ConveyorRatio_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ConveyorRatio_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ConveyorRatio_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ToleranceInner_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ToleranceInner_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ToleranceInner_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ToleranceOuter_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ToleranceOuter_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    ToleranceOuter_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    SelisihTebal_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    SelisihTebal_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    SelisihTebal_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    PitchYarn_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    PitchYarn_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    PitchYarn_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    DancerPosition_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    DancerPosition_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    DancerPosition_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    OdSensor_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    OdSensor_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    OdSensor_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    CuttingSpeed_Min = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    CuttingSpeed_Asli = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true),
                    CuttingSpeed_Max = table.Column<decimal>(type: "decimal(18,4)", precision: 18, scale: 4, nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SpsNoDocs", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "SpsItemLists",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    ItemList = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    SpsNoDocId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_SpsItemLists", x => x.Id);
                    table.ForeignKey(
                        name: "FK_SpsItemLists_SpsNoDocs_SpsNoDocId",
                        column: x => x.SpsNoDocId,
                        principalTable: "SpsNoDocs",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_SpsItemLists_SpsNoDocId",
                table: "SpsItemLists",
                column: "SpsNoDocId");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "SpsItemLists");

            migrationBuilder.DropTable(
                name: "SpsNoDocs");
        }
    }
}
